"""Adapter contract (methodology section 12, docs/architecture/adapter-contract.md)."""
from __future__ import annotations
from typing import Any, Protocol


class AgentAdapter(Protocol):
    def get_target_profile(self) -> dict[str, Any]: ...
    def health_check(self) -> dict[str, Any]: ...
    def create_session(self, actor_id: str, channel_context: str) -> str: ...
    def send_message(self, session_id: str, message: str,
                     attachments: list[dict] | None = None) -> dict[str, Any]: ...
    def get_transcript(self, session_id: str) -> list[dict[str, Any]]: ...
    def get_trace(self, session_id: str) -> list[dict[str, Any]]: ...
    def get_tool_calls(self, session_id: str) -> list[dict[str, Any]]: ...
    def get_authorization_events(self, session_id: str) -> list[dict[str, Any]]: ...
    def reset_session(self, session_id: str) -> None: ...
    def snapshot_state(self, scope: str) -> dict[str, Any]: ...
    def restore_state(self, snapshot: dict[str, Any]) -> None: ...


class AdapterError(Exception):
    pass
